[project]
name = "wepscraping-git"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "ipykernel>=7.3.0",
    "pandas>=3.0.5",
    "requests>=2.34.2",
    "selenium>=4.48.0",
]

[project.scripts]
wepscraping-git = "wepscraping_git:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
